/*
 * generated by Xtext
 */
package org.moflon.tgg.mosl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TGGStandaloneSetup extends TGGStandaloneSetupGenerated{

	public static void doSetup() {
		new TGGStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

