/**
 *
 * $Id$
 */
package org.emoflon.ibex.gt.StateModel.validation;

import org.eclipse.emf.common.util.EList;

import org.emoflon.ibex.gt.StateModel.IBeXMatch;
import org.emoflon.ibex.gt.StateModel.State;

/**
 * A sample validator interface for {@link org.emoflon.ibex.gt.StateModel.StateContainer}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StateContainerValidator {
	boolean validate();

	boolean validateStates(EList<State> value);

	boolean validateInitialState(State value);

	boolean validateInitialMatches(EList<IBeXMatch> value);
}
