/**
 *
 * $Id$
 */
package org.emoflon.ibex.gt.StateModel.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.emoflon.ibex.gt.StateModel.Link;

/**
 * A sample validator interface for {@link org.emoflon.ibex.gt.StateModel.StructuralDelta}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StructuralDeltaValidator {
	boolean validate();

	boolean validateCreatedObjects(EList<EObject> value);

	boolean validateDeletedObjects(EList<EObject> value);

	boolean validateCreatedLinks(EList<Link> value);

	boolean validateDeletedLinks(EList<Link> value);

	boolean validateDeletedRootLevelObjects(EList<EObject> value);

	boolean validateResource2EObjectContainment(EList<EObject> value);
}
