<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="IBeXTGGModel" nsURI="platform:/resource/org.emoflon.ibex.tgg.tggmodel/model/IBeXTGGModel.ecore"
    nsPrefix="IBeXTGGModel">
  <eClassifiers xsi:type="ecore:EClass" name="TGGModel" eSuperTypes="../../org.emoflon.ibex.common.coremodel/model/IBeXCoreModel.ecore#//IBeXModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondence" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ruleSet" lowerBound="1"
        eType="#//TGGRuleSet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeConstraintDefinitionLibraries"
        upperBound="-1" eType="#//CSP/TGGAttributeConstraintDefinitionLibrary" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TGGRuleSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//TGGRule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TGGRule" eSuperTypes="../../org.emoflon.ibex.common.coremodel/model/IBeXCoreModel.ecore#//IBeXRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//TGGNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//TGGEdge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondenceNodes" upperBound="-1"
        eType="#//TGGCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationalisations" upperBound="-1"
        eType="#//TGGOperationalRule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeConstraints" eType="#//CSP/TGGAttributeConstraintSet"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TGGOperationalRule" eSuperTypes="#//TGGRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationalisationMode"
        eType="#//OperationalisationMode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toBeMarked" eType="ecore:EClass ../../org.emoflon.ibex.common.coremodel/model/IBeXCoreModel.ecore#//IBeXRuleDelta"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alreadyMarked" eType="ecore:EClass ../../org.emoflon.ibex.common.coremodel/model/IBeXCoreModel.ecore#//IBeXRuleDelta"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TGGRuleElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainType" eType="#//DomainType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingType" eType="#//BindingType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TGGNode" eSuperTypes="../../org.emoflon.ibex.common.coremodel/model/IBeXCoreModel.ecore#//IBeXNode #//TGGRuleElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingCorrespondence"
        upperBound="-1" eType="#//TGGCorrespondence" eOpposite="#//TGGCorrespondence/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingCorrespondence"
        upperBound="-1" eType="#//TGGCorrespondence" eOpposite="#//TGGCorrespondence/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TGGCorrespondence" eSuperTypes="#//TGGNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//TGGNode" eOpposite="#//TGGNode/outgoingCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//TGGNode" eOpposite="#//TGGNode/incomingCorrespondence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TGGEdge" eSuperTypes="../../org.emoflon.ibex.common.coremodel/model/IBeXCoreModel.ecore#//IBeXEdge #//TGGRuleElement"/>
  <eClassifiers xsi:type="ecore:EEnum" name="OperationalisationMode">
    <eLiterals name="GENERATE"/>
    <eLiterals name="FORWARD" value="1"/>
    <eLiterals name="BACKWARD" value="2"/>
    <eLiterals name="CONSISTENCY_CHECK" value="3"/>
    <eLiterals name="CHECK_ONLY" value="4"/>
    <eLiterals name="SOURCE" value="5" literal="SOURCE"/>
    <eLiterals name="TARGET" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DomainType">
    <eLiterals name="SOURCE" literal="SOURCE"/>
    <eLiterals name="TARGET" value="1" literal="TARGET"/>
    <eLiterals name="CORRESPONDENCE" value="2" literal="CORRESPONDENCE"/>
    <eLiterals name="PROTOCOL" value="3" literal="PROTOCOL"/>
    <eLiterals name="PATTERN" value="4" literal="PATTERN"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BindingType">
    <eLiterals name="CONTEXT" literal="CONTEXT"/>
    <eLiterals name="CREATE" value="1" literal="CREATE"/>
    <eLiterals name="DELETE" value="2"/>
    <eLiterals name="NEGATIVE" value="3"/>
    <eLiterals name="RELAXED" value="4"/>
  </eClassifiers>
  <eSubpackages name="CSP" nsURI="platform:/resource/org.emoflon.ibex.tgg.tggmodel/model/IBeXTGGModel.ecore/CSP"
      nsPrefix="CSP">
    <eClassifiers xsi:type="ecore:EClass" name="TGGAttributeConstraintDefinition"
        eSuperTypes="../../org.emoflon.ibex.common.coremodel/model/IBeXCoreModel.ecore#//IBeXNamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterDefinitions"
          upperBound="-1" eType="#//CSP/TGGAttributeConstraintParameterDefinition"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="syncBindings" upperBound="-1"
          eType="#//CSP/TGGAttributeConstraintBinding" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="genBindings" upperBound="-1"
          eType="#//CSP/TGGAttributeConstraintBinding" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TGGAttributeConstraintDefinitionLibrary">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tggAttributeConstraintDefinitions"
          upperBound="-1" eType="#//CSP/TGGAttributeConstraintDefinition" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TGGAttributeConstraintParameterDefinition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EDataType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TGGAttributeConstraintBinding">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TGGAttributeConstraintSet">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tggAttributeConstraints"
          upperBound="-1" eType="#//CSP/TGGAttributeConstraint" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TGGAttributeConstraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="definition" eType="#//CSP/TGGAttributeConstraintDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//CSP/TGGAttributeConstraintParameterValue"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TGGAttributeConstraintVariable" eSuperTypes="../../org.emoflon.ibex.common.coremodel/model/IBeXCoreModel.ecore#//IBeXCoreArithmetic/ValueExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TGGAttributeConstraintParameterValue">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterDefinition"
          eType="#//CSP/TGGAttributeConstraintParameterDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
          eType="ecore:EClass ../../org.emoflon.ibex.common.coremodel/model/IBeXCoreModel.ecore#//IBeXCoreArithmetic/ValueExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TGGCSP" eSuperTypes="../../org.emoflon.ibex.common.coremodel/model/IBeXCoreModel.ecore#//IBeXNamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="package" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
          eType="ecore:EClass ../../org.emoflon.ibex.common.coremodel/model/IBeXCoreModel.ecore#//IBeXCoreArithmetic/ValueExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TGGLocalVariable" eSuperTypes="../../org.emoflon.ibex.common.coremodel/model/IBeXCoreModel.ecore#//IBeXNamedElement ../../org.emoflon.ibex.common.coremodel/model/IBeXCoreModel.ecore#//IBeXCoreArithmetic/ArithmeticExpression"/>
  </eSubpackages>
</ecore:EPackage>
