/**
 *
 * $Id$
 */
package org.emoflon.ibex.tgg.tggmodel.IBeXTGGModel.CSP.validation;

import org.eclipse.emf.common.util.EList;

import org.emoflon.ibex.tgg.tggmodel.IBeXTGGModel.CSP.TGGAttributeConstraintBinding;
import org.emoflon.ibex.tgg.tggmodel.IBeXTGGModel.CSP.TGGAttributeConstraintDefinitionLibrary;
import org.emoflon.ibex.tgg.tggmodel.IBeXTGGModel.CSP.TGGAttributeConstraintParameterDefinition;

/**
 * A sample validator interface for {@link org.emoflon.ibex.tgg.tggmodel.IBeXTGGModel.CSP.TGGAttributeConstraintDefinition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TGGAttributeConstraintDefinitionValidator {
	boolean validate();

	boolean validateParameterDefinitions(EList<TGGAttributeConstraintParameterDefinition> value);

	boolean validateSyncBindings(EList<TGGAttributeConstraintBinding> value);

	boolean validateGenBindings(EList<TGGAttributeConstraintBinding> value);

	boolean validateLibrary(TGGAttributeConstraintDefinitionLibrary value);
}
