<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="IBeXDisjunctPatternModel" nsURI="platform:/resource/org.emoflon.ibex.disjunctpatternmodel/model/IBeXDisjunctPatternModell.ecore"
    nsPrefix="IBeXDisjunctPatternModel">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Model for disjunct IBeXPatterns."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXDisjunctContextPattern" eSuperTypes="../../org.emoflon.ibex.patternmodel/model/IBeXPatternModel.ecore#//IBeXContext">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subpatterns" upperBound="-1"
        eType="ecore:EClass ../../org.emoflon.ibex.patternmodel/model/IBeXPatternModel.ecore#//IBeXContextPattern"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="injectivityConstraints"
        upperBound="-1" eType="#//IBeXDependentInjectivityConstraints" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributesConstraints"
        upperBound="-1" eType="#//IBeXDependentDisjunctAttribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXDisjunctAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPattern" eType="ecore:EClass ../../org.emoflon.ibex.patternmodel/model/IBeXPatternModel.ecore#//IBeXContextPattern"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="disjunctAttribute" upperBound="-1"
        eType="ecore:EClass ../../org.emoflon.ibex.patternmodel/model/IBeXPatternModel.ecore#//IBeXAttributeConstraint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcePattern" upperBound="-1"
        eType="ecore:EClass ../../org.emoflon.ibex.patternmodel/model/IBeXPatternModel.ecore#//IBeXContextPattern"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXDependentInjectivityConstraints">
    <eStructuralFeatures xsi:type="ecore:EReference" name="injectivityConstraints"
        upperBound="-1" eType="#//IBexDisjunctInjectivityConstraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patterns" upperBound="-1"
        eType="ecore:EClass ../../org.emoflon.ibex.patternmodel/model/IBeXPatternModel.ecore#//IBeXContextPattern"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeConstraints" upperBound="-1"
        eType="#//IBeXDependentDisjunctAttribute" eOpposite="#//IBeXDependentDisjunctAttribute/injectivityConstraints"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBexDisjunctInjectivityConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pattern1" eType="ecore:EClass ../../org.emoflon.ibex.patternmodel/model/IBeXPatternModel.ecore#//IBeXContextPattern"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pattern2" eType="ecore:EClass ../../org.emoflon.ibex.patternmodel/model/IBeXPatternModel.ecore#//IBeXContextPattern"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node1" upperBound="-1"
        eType="ecore:EClass ../../org.emoflon.ibex.patternmodel/model/IBeXPatternModel.ecore#//IBeXNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node2" upperBound="-1"
        eType="ecore:EClass ../../org.emoflon.ibex.patternmodel/model/IBeXPatternModel.ecore#//IBeXNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXDependentDisjunctAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//IBeXDisjunctAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependentPatterns" upperBound="-1"
        eType="ecore:EClass ../../org.emoflon.ibex.patternmodel/model/IBeXPatternModel.ecore#//IBeXContextPattern"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="injectivityConstraints"
        eType="#//IBeXDependentInjectivityConstraints" eOpposite="#//IBeXDependentInjectivityConstraints/attributeConstraints"/>
  </eClassifiers>
</ecore:EPackage>
