/*
 * generated by Xtext
 */
package org.moflon.tgg.mosl.ui;



import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ide.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ide.editor.syntaxcoloring.DefaultSemanticHighlightingCalculator;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.moflon.tgg.mosl.ui.highlighting.MOSLHighlightingConfiguration;
import org.moflon.tgg.mosl.ui.highlighting.MOSLSemanticHighlightCalculator;
import org.moflon.tgg.mosl.ui.highlighting.MOSLTokenMapper;
import org.moflon.tgg.mosl.ui.highlighting.utils.MOSLHighlightProviderHelper;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TGGUiModule extends org.moflon.tgg.mosl.ui.AbstractTGGUiModule {
	public TGGUiModule(AbstractUIPlugin plugin) {
		super(plugin);
		MOSLHighlightProviderHelper.init();
	}
	
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration()
	{
	   return MOSLHighlightingConfiguration.class;
	}
	
	@Override
	public void configure(Binder binder) {
		binder.bind(DefaultSemanticHighlightingCalculator.class).to(MOSLSemanticHighlightCalculator.class);
		binder.bind(AbstractAntlrTokenToAttributeIdMapper.class).to(MOSLTokenMapper.class);
		super.configure(binder);
		
	}
}
