/**
 *
 * $Id$
 */
package org.emoflon.ibex.tgg.tggmodel.IBeXTGGModel.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EPackage;

import org.emoflon.ibex.tgg.tggmodel.IBeXTGGModel.CSP.TGGAttributeConstraintDefinitionLibrary;

import org.emoflon.ibex.tgg.tggmodel.IBeXTGGModel.TGGRuleSet;

/**
 * A sample validator interface for {@link org.emoflon.ibex.tgg.tggmodel.IBeXTGGModel.TGGModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TGGModelValidator {
	boolean validate();

	boolean validateSource(EList<EPackage> value);

	boolean validateTarget(EList<EPackage> value);

	boolean validateCorrespondence(EPackage value);

	boolean validateRuleSet(TGGRuleSet value);

	boolean validateAttributeConstraintDefinitionLibraries(EList<TGGAttributeConstraintDefinitionLibrary> value);
}
