/**
 *
 * $Id$
 */
package org.emoflon.ibex.tgg.tggmodel.IBeXTGGModel.validation;

import org.eclipse.emf.common.util.EList;

import org.emoflon.ibex.common.coremodel.IBeXCoreModel.IBeXAttributeAssignment;
import org.emoflon.ibex.common.coremodel.IBeXCoreModel.IBeXCoreArithmetic.BooleanExpression;
import org.emoflon.ibex.tgg.tggmodel.IBeXTGGModel.TGGCorrespondence;

/**
 * A sample validator interface for {@link org.emoflon.ibex.tgg.tggmodel.IBeXTGGModel.TGGNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TGGNodeValidator {
	boolean validate();

	boolean validateIncomingCorrespondence(EList<TGGCorrespondence> value);

	boolean validateOutgoingCorrespondence(EList<TGGCorrespondence> value);

	boolean validateAttributeAssignments(EList<IBeXAttributeAssignment> value);

	boolean validateReferencedByConditions(EList<BooleanExpression> value);
}
