/**
 *
 * $Id$
 */
package org.emoflon.ibex.modelXML.validation;

import org.emoflon.ibex.modelXML.Node;

/**
 * A sample validator interface for {@link org.emoflon.ibex.modelXML.XMLModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface XMLModelValidator {
	boolean validate();

	boolean validateRoot(Node value);

	boolean validateHeader(String value);
}
