<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Families" nsURI="platform:/resource/FamiliesToPersonsDeterministic/model/Families.ecore"
    nsPrefix="Families">
  <eClassifiers xsi:type="ecore:EClass" name="FamilyRegister">
    <eStructuralFeatures xsi:type="ecore:EReference" name="families" upperBound="-1"
        eType="#//Family" containment="true" eOpposite="#//Family/familiesInverse"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Family">
    <eStructuralFeatures xsi:type="ecore:EReference" name="father" eType="#//FamilyMember"
        containment="true" eOpposite="#//FamilyMember/fatherInverse"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mother" eType="#//FamilyMember"
        containment="true" eOpposite="#//FamilyMember/motherInverse"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sons" upperBound="-1" eType="#//FamilyMember"
        containment="true" eOpposite="#//FamilyMember/sonsInverse"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daughters" upperBound="-1"
        eType="#//FamilyMember" containment="true" eOpposite="#//FamilyMember/daughtersInverse"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="familiesInverse" eType="#//FamilyRegister"
        eOpposite="#//FamilyRegister/families"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FamilyMember">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fatherInverse" eType="#//Family"
        eOpposite="#//Family/father"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="motherInverse" eType="#//Family"
        eOpposite="#//Family/mother"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sonsInverse" eType="#//Family"
        eOpposite="#//Family/sons"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daughtersInverse" eType="#//Family"
        eOpposite="#//Family/daughters"/>
  </eClassifiers>
</ecore:EPackage>
