<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="FamiliesToPersonsDeterministic" nsURI="platform:/resource/FamiliesToPersonsDeterministic/model/FamiliesToPersonsDeterministic.ecore"
    nsPrefix="FamiliesToPersonsDeterministic">
  <eClassifiers xsi:type="ecore:EClass" name="RegisterToRegister">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/FamiliesToPersonsDeterministic/model/Families.ecore#//FamilyRegister"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/FamiliesToPersonsDeterministic/model/Persons.ecore#//PersonRegister"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MemberToPerson">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/FamiliesToPersonsDeterministic/model/Families.ecore#//FamilyMember"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/FamiliesToPersonsDeterministic/model/Persons.ecore#//Person"/>
  </eClassifiers>
</ecore:EPackage>
