<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="language" nsURI="platform:/plugin/org.emoflon.ibex.tgg.core.language/model/Language.ecore"
    nsPrefix="language">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Internal, IBeX-specific, TGG Metamodel for defining TGG Rules"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="TGG" eSuperTypes="#//TGGNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trg" upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="corr" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//TGGRule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeConstraintDefinitionLibrary"
        lowerBound="1" eType="#//TGGAttributeConstraintDefinitionLibrary" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TGGRule" eSuperTypes="#//TGGNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refines" upperBound="-1"
        eType="#//TGGRule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nacs" upperBound="-1" eType="#//NAC"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//TGGRuleNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//TGGRuleEdge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeConditionLibrary"
        lowerBound="1" eType="#//TGGAttributeConstraintLibrary" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TGGRuleElement" abstract="true" eSuperTypes="#//TGGNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainType" eType="#//DomainType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingType" eType="#//BindingType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TGGRuleNode" eSuperTypes="#//TGGRuleElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingEdges" upperBound="-1"
        eType="#//TGGRuleEdge" eOpposite="#//TGGRuleEdge/trgNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingEdges" upperBound="-1"
        eType="#//TGGRuleEdge" eOpposite="#//TGGRuleEdge/srcNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingCorrsSource" upperBound="-1"
        eType="#//TGGRuleCorr" eOpposite="#//TGGRuleCorr/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingCorrsTarget" upperBound="-1"
        eType="#//TGGRuleCorr" eOpposite="#//TGGRuleCorr/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attrExpr" upperBound="-1"
        eType="#//TGGInplaceAttributeExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TGGRuleCorr" eSuperTypes="#//TGGRuleNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//TGGRuleNode"
        eOpposite="#//TGGRuleNode/incomingCorrsSource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//TGGRuleNode"
        eOpposite="#//TGGRuleNode/incomingCorrsTarget"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TGGRuleEdge" eSuperTypes="#//TGGRuleElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="srcNode" eType="#//TGGRuleNode"
        eOpposite="#//TGGRuleNode/outgoingEdges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trgNode" eType="#//TGGRuleNode"
        eOpposite="#//TGGRuleNode/incomingEdges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DomainType">
    <eLiterals name="SRC" literal="SRC"/>
    <eLiterals name="TRG" value="1" literal="TRG"/>
    <eLiterals name="CORR" value="2" literal="CORR"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BindingType">
    <eLiterals name="CONTEXT" literal="CONTEXT"/>
    <eLiterals name="CREATE" value="1" literal="CREATE"/>
    <eLiterals name="DELETE" value="2"/>
    <eLiterals name="NEGATIVE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NAC" eSuperTypes="#//TGGNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//TGGRuleNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//TGGRuleEdge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeConditionLibrary"
        lowerBound="1" eType="#//TGGAttributeConstraintLibrary" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TGGInplaceAttributeExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueExpr" eType="#//TGGExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//TGGAttributeConstraintOperators" defaultValueLiteral="EQUAL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TGGAttributeConstraintOperators">
    <eLiterals name="EQUAL" literal="EQUAL"/>
    <eLiterals name="UNEQUAL" value="1" literal="UNEQUAL"/>
    <eLiterals name="GR_EQUAL" value="2" literal="GR_EQUAL"/>
    <eLiterals name="LE_EQUAL" value="3" literal="LE_EQUAL"/>
    <eLiterals name="GREATER" value="4" literal="GREATER"/>
    <eLiterals name="LESSER" value="5" literal="LESSER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TGGAttributeConstraintLibrary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tggAttributeConstraints"
        upperBound="-1" eType="#//TGGAttributeConstraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterValues" upperBound="-1"
        eType="#//TGGParamValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TGGAttributeConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" eType="#//TGGAttributeConstraintDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//TGGParamValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TGGAttributeVariable" eSuperTypes="#//TGGParamValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TGGAttributeConstraintDefinitionLibrary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tggAttributeConstraintDefinitions"
        upperBound="-1" eType="#//TGGAttributeConstraintDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TGGAttributeConstraintDefinition" eSuperTypes="#//TGGNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userDefined" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterDefinitions" upperBound="-1"
        eType="#//TGGAttributeConstraintParameterDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="syncAdornments" upperBound="-1"
        eType="#//TGGAttributeConstraintAdornment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genAdornments" upperBound="-1"
        eType="#//TGGAttributeConstraintAdornment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TGGAttributeConstraintParameterDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EDataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TGGAttributeConstraintAdornment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TGGNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TGGParamValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterDefinition" eType="#//TGGAttributeConstraintParameterDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TGGExpression" abstract="true" eSuperTypes="#//TGGParamValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="TGGLiteralExpression" eSuperTypes="#//TGGExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TGGEnumExpression" eSuperTypes="#//TGGExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eenum" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="literal" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EEnumLiteral"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TGGAttributeExpression" eSuperTypes="#//TGGExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectVar" eType="#//TGGRuleNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
  </eClassifiers>
  <eSubpackages name="repair" nsURI="platform:/plugin/org.emoflon.ibex.tgg.core.language/model/Language.ecore#/repair"
      nsPrefix="repair">
    <eClassifiers xsi:type="ecore:EClass" name="ExternalShortcutRule">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sourceRule" eType="#//TGGRule"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetRule" eType="#//TGGRule"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="deletions" upperBound="-1"
          eType="#//TGGRuleElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="creations" upperBound="-1"
          eType="#//TGGRuleElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="unboundSrcContext" upperBound="-1"
          eType="#//TGGRuleElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="unboundTrgContext" upperBound="-1"
          eType="#//TGGRuleElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" upperBound="-1"
          eType="#//repair/TGGRuleElementMapping" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TGGRuleElementMapping">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sourceRuleElement" eType="#//TGGRuleElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetRuleElement" eType="#//TGGRuleElement"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
