<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="IBeXLanguage" nsURI="platform:/plugin/org.emoflon.ibex.common/IBeXLanguage.ecore"
    nsPrefix="org.emoflon.ibex.common.common.language">
  <eClassifiers xsi:type="ecore:EClass" name="IBeXEdge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceNode" eType="#//IBeXNode"
        eOpposite="#//IBeXNode/outgoingEdges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetNode" eType="#//IBeXNode"
        eOpposite="#//IBeXNode/incomingEdges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBexNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXNode" eSuperTypes="#//IBexNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingEdges" upperBound="-1"
        eType="#//IBeXEdge" eOpposite="#//IBeXEdge/targetNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingEdges" upperBound="-1"
        eType="#//IBeXEdge" eOpposite="#//IBeXEdge/sourceNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXNodeToNodeMapping" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//IBeXNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//IBeXNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXPattern" eSuperTypes="#//IBexNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="localEdges" upperBound="-1"
        eType="#//IBeXEdge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localNodes" upperBound="-1"
        eType="#//IBeXNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="negativeInvocations" upperBound="-1"
        eType="#//IBeXPatternInvocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="positiveInvocations" upperBound="-1"
        eType="#//IBeXPatternInvocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signatureNodes" upperBound="-1"
        eType="#//IBeXNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXPatternInvocation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="invokedBy" eType="#//IBeXPattern"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoking" eType="#//IBeXPattern"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" upperBound="-1"
        eType="#//IBeXNodeToNodeMapping" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
