<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="StochasticLanguage" nsURI="platform:/resource/org.emoflon.ibex.common/model/StochasticExtension.ecore"
    nsPrefix="StochasticLangugae">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Model for the Stochastic Extension of the EMoflon API."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="GTStochasticNamedElement" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Any element in the internal model which has a name should inherit form this class."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GTStochasticNode" eSuperTypes="#//GTStochasticNamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A typed node can reference other nodes via edges."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GTAttribute" eSuperTypes="#//GTStochasticNode #//GTArithmetics">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Attributes can be used as parameters for stochastic functions."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="negative" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GTStochasticFunction">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A stochastic function can be used to calculate probabilities or generate values."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mean" eType="#//GTArithmetics"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sd" eType="#//GTArithmetics"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distribution" eType="#//GTStochasticDistribution"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GTStochasticDistribution">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The stochastic distribution type. WARNING: Literals need to be the same as the GT.xtext distribution type"/>
    </eAnnotations>
    <eLiterals name="NORMAL"/>
    <eLiterals name="UNIFORM" value="1"/>
    <eLiterals name="EXPONENTIAL" value="2"/>
    <eLiterals name="STATIC" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GTStochasticRange">
    <eLiterals name="NEUTRAL"/>
    <eLiterals name="POSITIVE" value="1"/>
    <eLiterals name="NEGATIVE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GTNumber" eSuperTypes="#//GTArithmetics">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The value of the parameter if it has a static value"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GTArithmetics" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GTTwoParameterCalculation" eSuperTypes="#//GTArithmetics">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//GTArithmetics"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//GTArithmetics"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//TwoParameterOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GTOneParameterCalculation" eSuperTypes="#//GTArithmetics">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//GTArithmetics"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//OneParameterOperator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="negative" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TwoParameterOperator">
    <eLiterals name="ADDITION"/>
    <eLiterals name="MULTIPLICATION" value="1"/>
    <eLiterals name="DIVISION" value="2"/>
    <eLiterals name="MODULO" value="3"/>
    <eLiterals name="EXPONENTIAL" value="4"/>
    <eLiterals name="SUBTRACTION" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OneParameterOperator">
    <eLiterals name="ROOT"/>
    <eLiterals name="ABSOLUTE" value="1"/>
    <eLiterals name="SIN" value="2"/>
    <eLiterals name="COS" value="3"/>
    <eLiterals name="TAN" value="4"/>
    <eLiterals name="E_EXPONENTIAL" value="5"/>
    <eLiterals name="LOGARITHMUS" value="6"/>
    <eLiterals name="NATLOG" value="7"/>
    <eLiterals name="BRACKET" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GTRelation">
    <eLiterals name="GREATER_OR_EQUAL"/>
    <eLiterals name="GREATER" value="1"/>
    <eLiterals name="EQUAL" value="2"/>
    <eLiterals name="UNEQUAL" value="3"/>
    <eLiterals name="SMALLER_OR_EQUAL" value="4"/>
    <eLiterals name="SMALLER" value="5"/>
  </eClassifiers>
</ecore:EPackage>
