<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="IBeXPatternModel" nsURI="platform:/resource/org.emoflon.ibex.patternmodel/model/IBeXPatternModel.ecore"
    nsPrefix="IBeXPatternModel">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Model for IBeXPatterns."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXModel">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A set of IBeXPatterns. Each pattern in a set must have an unique name."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patternSet" lowerBound="1"
        eType="#//IBeXPatternSet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ruleSet" lowerBound="1"
        eType="#//IBeXRuleSet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeSet" lowerBound="1"
        eType="#//IBeXNodeSet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edgeSet" lowerBound="1"
        eType="#//IBeXEdgeSet" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXPatternSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextPatterns" upperBound="-1"
        eType="#//IBeXContext" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXRuleSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//IBeXRule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXNodeSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//IBeXNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXEdgeSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//IBeXEdge" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXNamedElement" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Any IBeX element which has a name should inherit form this class."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXPattern" abstract="true" eSuperTypes="#//IBeXNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasCountExpression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXContext" abstract="true" eSuperTypes="#//IBeXPattern">
    <eStructuralFeatures xsi:type="ecore:EReference" name="apiPatternDependencies"
        upperBound="-1" eType="#//IBeXContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXContextAlternatives" eSuperTypes="#//IBeXContext">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alternativePatterns" upperBound="-1"
        eType="#//IBeXContextPattern" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
        eType="#//IBeXContextPattern" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXContextPattern" eSuperTypes="#//IBeXContext">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A pattern consists of local edges and nodes, signature nodes. It can invoke other patterns and force nodes be different."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeConstraint" upperBound="-1"
        eType="#//IBeXAttributeConstraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arithmeticConstraints"
        upperBound="-1" eType="#//IBeXArithmeticConstraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="injectivityConstraints"
        upperBound="-1" eType="#//IBeXInjectivityConstraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invocations" upperBound="-1"
        eType="#//IBeXPatternInvocation" containment="true" eOpposite="#//IBeXPatternInvocation/invokedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localEdges" upperBound="-1"
        eType="#//IBeXEdge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localNodes" upperBound="-1"
        eType="#//IBeXNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signatureNodes" upperBound="-1"
        eType="#//IBeXNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="csps" upperBound="-1" eType="#//IBeXCSP"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//IBeXParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXCreatePattern" eSuperTypes="#//IBeXPattern">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A pattern for creation defines which nodes and edges are created. Nodes which are not created, but source or target node of a created edge are context nodes."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeAssignments" upperBound="-1"
        eType="#//IBeXAttributeAssignment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextNodes" upperBound="-1"
        eType="#//IBeXNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="createdEdges" upperBound="-1"
        eType="#//IBeXEdge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="createdNodes" upperBound="-1"
        eType="#//IBeXNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXDeletePattern" eSuperTypes="#//IBeXPattern">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A pattern for deletion defines which nodes and edges are deleted. Nodes which are not deleted, but source or target node of a deleted edge are context nodes."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextNodes" upperBound="-1"
        eType="#//IBeXNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deletedEdges" upperBound="-1"
        eType="#//IBeXEdge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deletedNodes" upperBound="-1"
        eType="#//IBeXNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXNode" eSuperTypes="#//IBeXNamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A typed node can reference other nodes via edges."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingEdges" upperBound="-1"
        eType="#//IBeXEdge" eOpposite="#//IBeXEdge/targetNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingEdges" upperBound="-1"
        eType="#//IBeXEdge" eOpposite="#//IBeXEdge/sourceNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXEdge" eSuperTypes="#//IBeXNamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A typed edge connects two nodes. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceNode" eType="#//IBeXNode"
        eOpposite="#//IBeXNode/outgoingEdges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetNode" eType="#//IBeXNode"
        eOpposite="#//IBeXNode/incomingEdges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXParameter" eSuperTypes="#//IBeXNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EDataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IBeXRelation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The relations for attribute constraints."/>
    </eAnnotations>
    <eLiterals name="GREATER_OR_EQUAL"/>
    <eLiterals name="GREATER" value="1"/>
    <eLiterals name="EQUAL" value="2"/>
    <eLiterals name="UNEQUAL" value="3"/>
    <eLiterals name="SMALLER_OR_EQUAL" value="4"/>
    <eLiterals name="SMALLER" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXAttribute" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The super class for attribute assignments and constraints."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXAttributeAssignment" eSuperTypes="#//IBeXAttribute">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An attribute assignment sets the attribute value."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//IBeXAttributeValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" eType="#//IBeXNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXAttributeConstraint" eSuperTypes="#//IBeXAttribute #//IBeXConstraint">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A constraint defines a relation which must hold for a certain attribute of a node."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relation" eType="#//IBeXRelation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="#//IBeXAttributeValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" eType="#//IBeXAttributeValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXAttributeValue">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The value of an attribute constraint or assignment."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXAttributeParameter" eSuperTypes="#//IBeXAttributeValue #//IBeXNamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An attribute value whose value is determined by a parameter."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXConstant" eSuperTypes="#//IBeXAttributeValue">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A wrapper for an object as attribute value."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXEnumLiteral" eSuperTypes="#//IBeXAttributeValue">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A wrapper for an EnumLiteral value as an attribute value."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="literal" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EEnumLiteral"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXAttributeExpression" eSuperTypes="#//IBeXAttributeValue">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An attribute expression points to the attribute value of a node."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" eType="#//IBeXNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXStochasticAttributeValue" eSuperTypes="#//IBeXAttributeValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="range" eType="#//IBeXDistributionRange"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="#//IBeXProbabilityDistribution"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXArithmeticValue" eSuperTypes="#//IBeXAttributeValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//IBeXArithmeticExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXInjectivityConstraint">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A pair of nodes."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" lowerBound="2"
        upperBound="2" eType="#//IBeXNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXPatternInvocation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An invocation of an IBeXPattern. Invocations can be positive or negative."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="positive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invokedBy" eType="#//IBeXContextPattern"
        eOpposite="#//IBeXContextPattern/invocations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invokedPattern" eType="#//IBeXContextPattern"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" upperBound="-1"
        eType="#//IBeXNodeToNodeMapping" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXNodeToNodeMapping" instanceClassName="java.util.Map$Entry">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A mapping between nodes."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//IBeXNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//IBeXNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXCSP">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A pattern consists of local edges and nodes, signature nodes. It can invoke other patterns and force nodes be different."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="package" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//IBeXAttributeValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXRule" eSuperTypes="#//IBeXNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" eType="#//IBeXContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" eType="#//IBeXContextPattern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="create" eType="#//IBeXCreatePattern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="delete" eType="#//IBeXDeletePattern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forEach" upperBound="-1"
        eType="#//IBeXForEachExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//IBeXParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arithmeticConstraints"
        upperBound="-1" eType="#//IBeXArithmeticConstraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="probability" eType="#//IBeXProbability"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXForEachExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="create" eType="#//IBeXCreatePattern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="delete" eType="#//IBeXDeletePattern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//IBeXNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trgIterator" lowerBound="1"
        eType="#//IBeXNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edge" lowerBound="1" eType="#//IBeXEdge"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="createdEdges" upperBound="-1"
        eType="#//IBeXEdge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deletedEdges" upperBound="-1"
        eType="#//IBeXEdge" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXProbability">
    <eStructuralFeatures xsi:type="ecore:EReference" name="distribution" lowerBound="1"
        eType="#//IBeXProbabilityDistribution" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
        eType="#//IBeXArithmeticExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXConstraint" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXArithmeticConstraint" eSuperTypes="#//IBeXConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="#//IBeXArithmeticExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relation" lowerBound="1"
        eType="#//IBeXRelation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" eType="#//IBeXArithmeticExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXArithmeticExpression" abstract="true"
      interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXUnaryExpression" eSuperTypes="#//IBeXArithmeticExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" lowerBound="1"
        eType="#//IBeXArithmeticExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//IBeXUnaryOperator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="negative" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXBinaryExpression" eSuperTypes="#//IBeXArithmeticExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//IBeXArithmeticExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//IBeXArithmeticExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//IBeXBinaryOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXArithmeticValueLiteral" eSuperTypes="#//IBeXArithmeticExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IBeXBinaryOperator">
    <eLiterals name="ADDITION"/>
    <eLiterals name="MULTIPLICATION" value="1"/>
    <eLiterals name="DIVISION" value="2"/>
    <eLiterals name="MODULUS" value="3"/>
    <eLiterals name="EXPONENTIATION" value="4"/>
    <eLiterals name="SUBTRACTION" value="5"/>
    <eLiterals name="MINIMUM" value="6"/>
    <eLiterals name="MAXIMUM" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IBeXUnaryOperator">
    <eLiterals name="SQRT"/>
    <eLiterals name="ABSOLUTE" value="1"/>
    <eLiterals name="SIN" value="2"/>
    <eLiterals name="COS" value="3"/>
    <eLiterals name="TAN" value="4"/>
    <eLiterals name="E_EXPONENTIAL" value="5"/>
    <eLiterals name="LOG" value="6"/>
    <eLiterals name="LG" value="7"/>
    <eLiterals name="BRACKET" value="8"/>
    <eLiterals name="COUNT" value="9" literal="COUNT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXProbabilityDistribution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mean" eType="#//IBeXArithmeticExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stddev" eType="#//IBeXArithmeticExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//IBeXDistributionType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IBeXDistributionType">
    <eLiterals name="NORMAL"/>
    <eLiterals name="UNIFORM" value="1"/>
    <eLiterals name="EXPONENTIAL" value="2"/>
    <eLiterals name="STATIC" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXArithmeticAttribute" eSuperTypes="#//IBeXNode #//IBeXArithmeticExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="negative" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IBeXDistributionRange">
    <eLiterals name="ALL"/>
    <eLiterals name="POSITIVE_ONLY" value="1"/>
    <eLiterals name="NEGATIVE_ONLY" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBeXMatchCount" eSuperTypes="#//IBeXUnaryExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="invocation" lowerBound="1"
        eType="#//IBeXPatternInvocation" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
