/**
 *
 * $Id$
 */
package org.emoflon.ibex.patternmodel.IBeXPatternModel.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.emoflon.ibex.patternmodel.IBeXPatternModel.IBeXEdge;

/**
 * A sample validator interface for {@link org.emoflon.ibex.patternmodel.IBeXPatternModel.IBeXNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IBeXNodeValidator {
	boolean validate();

	boolean validateIncomingEdges(EList<IBeXEdge> value);

	boolean validateOutgoingEdges(EList<IBeXEdge> value);

	boolean validateType(EClass value);
}
