/**
 *
 * $Id$
 */
package org.emoflon.ibex.patternmodel.IBeXPatternModel.validation;

import org.eclipse.emf.ecore.EAttribute;

import org.emoflon.ibex.patternmodel.IBeXPatternModel.IBeXAttributeValue;
import org.emoflon.ibex.patternmodel.IBeXPatternModel.IBeXNode;

/**
 * A sample validator interface for {@link org.emoflon.ibex.patternmodel.IBeXPatternModel.IBeXAttributeAssignment}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IBeXAttributeAssignmentValidator {
	boolean validate();

	boolean validateValue(IBeXAttributeValue value);

	boolean validateNode(IBeXNode value);

	boolean validateType(EAttribute value);
}
