<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SimpleFamilies" nsURI="platform:/resource/SimpleFamilies/model/SimpleFamilies.ecore"
    nsPrefix="SimpleFamilies">
  <eClassifiers xsi:type="ecore:EClass" name="FamilyRegister">
    <eStructuralFeatures xsi:type="ecore:EReference" name="families" upperBound="5"
        eType="#//Family" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Family">
    <eStructuralFeatures xsi:type="ecore:EReference" name="father" eType="#//FamilyMember"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mother" eType="#//FamilyMember"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sons" upperBound="-1" eType="#//FamilyMember"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daughters" upperBound="-1"
        eType="#//FamilyMember" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FamilyMember">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
